# Generated by Django 5.1.6 on 2025-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200)),
                ('soldier_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('passport_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier_name', models.CharField(max_length=200)),
                ('reporter_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('injury_description', models.TextField()),
                ('treatment_given', models.TextField()),
                ('estimated_bill', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_carrier', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('minute_requested', models.CharField(max_length=200)),
                ('country_of_deploy', models.CharField(max_length=200)),
                ('name_of_soldier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrackSoldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='usdefencsupport/img/')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=200)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=200)),
                ('kids', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('grade_a', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('grade_b', models.CharField(max_length=200)),
            ],
        ),
    ]
