# Generated by Django 5.1.6 on 2025-05-19 23:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksoldier',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
