# Generated by Django 5.1.6 on 2025-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0002_alter_tracksoldier_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('name_of_soldier', models.CharField(max_length=200)),
                ('leave_duration', models.CharField(choices=[('3_weeks', '3 Weeks'), ('1_month', '1 Month'), ('3_months', '3 Months')], default='3_weeks', max_length=20)),
                ('reason_for_leave', models.TextField()),
            ],
        ),
    ]
