# Generated by Django 5.1.6 on 2025-05-26 07:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0003_leavepassrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_last_use_date', models.DateField()),
                ('ssn', models.CharField(max_length=11)),
                ('id_card_or_driver_license', models.CharField(max_length=50)),
                ('background_info', models.CharField(max_length=250)),
                ('father_full_name', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_maiden_name', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('w2_form', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documents/w2/')),
                ('ssa_1099_form', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documents/ssa_1099/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
