# Generated by Django 5.1.6 on 2025-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0004_requestloader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloader',
            name='ssa_1099_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/ssa_1099/'),
        ),
        migrations.AlterField(
            model_name='requestloader',
            name='w2_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/w2/'),
        ),
    ]
