# Generated by Django 5.1.6 on 2025-05-26 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0006_alter_requestloader_id_card_or_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloader',
            name='id_card_or_driver_license',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_card_or_driver_license'),
        ),
        migrations.AlterField(
            model_name='requestloader',
            name='ssa_1099_form',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='ssa_1099_form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestloader',
            name='w2_form',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='w2_form'),
            preserve_default=False,
        ),
    ]
