# Generated by Django 5.1.6 on 2025-05-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0007_alter_requestloader_id_card_or_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloader',
            name='ssa_1099_form',
            field=models.FileField(upload_to='ssa_1099_form'),
        ),
        migrations.AlterField(
            model_name='requestloader',
            name='w2_form',
            field=models.FileField(upload_to='w2_form'),
        ),
    ]
