# Generated by Django 5.1.7 on 2025-06-05 04:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usdefencsupport', '0008_alter_requestloader_ssa_1099_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloader',
            name='ssa_1099_form',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='ssa_1099_form'),
        ),
        migrations.AlterField(
            model_name='requestloader',
            name='w2_form',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='w2_form'),
        ),
    ]
